f1r4: 会話中に前の部屋に戻れる問題を修正
2022-4J-group-O/Main pull request #106
Opened 2023-02-11 00:33 UTC by tt6-mzn

# 実装した内容

f1r4の会話が、イベントとして呼ばれていないので、ボタンが押せてしまう問題を修正

* 大まかな実装内容

会話をイベントにしただけ

## デバッグしてほしいところ

動く？

2023-02-11 08:03 UTC, Esu0 requested changes
テスト時に変えた変更が残ってるかな

2023-02-11 08:03 UTC, Esu0 commented on game/script.rpy
> -    jump title
戻しといて

2023-02-12 15:39 UTC, tt6-mzn commented
修正しました

2023-02-12 15:56 UTC, Esu0 approved these changes
直った

2023-02-12 15:57 UTC, merged