f2r3のバグ部屋からメニューまでを追加
2022-4J-group-O/Main pull request #111
Opened 2023-02-11 15:11 UTC by tt6-mzn

# 実装した内容

f2r3のバグ部屋と、そのあとのメニュー画面でのイベントを追加しました。

## デバッグしてほしいところ

フラグ回り怪しいので要チェック

2023-02-11 15:51 UTC, Esu0 requested changes
エラーと不具合が起きたから直しておいて

2023-02-11 15:51 UTC, Esu0 commented on game/scripts/menu/events/opening_f3.rpy
> +    show girl at right with dissolve
タブがあるっぽい

2023-02-11 15:51 UTC, Esu0 commented on game/scripts/menu/events/opening_f3.rpy
> +
タブがあるっぽい

2023-02-11 15:51 UTC, Esu0 commented on game/scripts/menu/start.rpy
> +        $ Event("menu2_ev_opening_f3")
後ろの括弧が抜けてる

2023-02-11 15:51 UTC, Esu0 requested changes
エラーと不具合が起きたから直しておいて

2023-02-12 15:24 UTC, tt6-mzn commented
修正しました

2023-02-12 16:00 UTC, Esu0 reviewed
LGTM

2023-02-12 16:00 UTC, Esu0 approved these changes
LGTM

2023-02-12 16:00 UTC, merged