f2r1の様々な部分を改善
2022-4J-group-O/Main pull request #112
Opened 2023-02-12 15:52 UTC by Esu0

# 実装した内容

* f2r1の`picture frame A`などのディレクトリの内容によって絵画がエラーメッセージになるように変更
* オブジェを置く台の画像の参照元を一つの画像にした
* `default_game_data`の中身がでたらめだったので変更
* `box`が表示される条件を、ディレクトリ内容に依存する形で変更
* ディレクトリの初期化処理を追加
* その他あるかも

## 追加した関数

* ローカル関数なので省略

## デバッグしてほしいところ

* 今まで通り動くか

## 既知のバグ

* 右マップだと少女が表示されない

2023-02-12 17:02 UTC, tt6-mzn requested changes
軽微な部分だけ修正してもろて
それ以外は動いてると思う

2023-02-12 17:02 UTC, tt6-mzn commented on game/scripts/f2/r1/start.rpy
s/objectC/object C
やね

2023-02-12 17:02 UTC, tt6-mzn commented on game/scripts/f2/r1/start.rpy
> +        check_folder_new(config.basedir, user_directory, box_path)
引数三つになってる

2023-02-12 17:18 UTC, Esu0 commented
でけた

2023-02-13 13:15 UTC, tt6-mzn requested changes

2023-02-13 13:15 UTC, tt6-mzn commented on game/scripts/f2/r1/start.rpy
> +        return os.path.isdir(os.path.join(config.basedir, user_directory, box_path))
パスが間違ってる

2023-02-13 13:28 UTC, tt6-mzn approved these changes
ok

2023-02-13 13:31 UTC, merged