Make f2 renew
2022-4J-group-O/Main pull request #51
Opened 2022-12-21 13:20 UTC by nmrintel

# 実装した内容

* f2r1が動くようになりました。

1. メニューからf2へジャンプ
2. object2にあるAppleとobject3へ移動
3. クリア (キャラがしゃべる＆画面上にshelfが表示&boxディレクトリができる)

## 追加した変数・フラグ

* f2r1_exsist: Appleがobject3にあるか(クリアしてるか)
* f2r1_first:　もうクリア時の処理はしたか(クリア後にキャラがまた話すのを防止)

## その他の変更
menuとかでf2に直接とべるように改変してあるので、完成版では修正が必要

## デバッグしてほしいところ
動くかどうか

## 既知のバグ

2022-12-24 13:38 UTC, tt6-mzn requested changes
誤字と変数名の間違い、`f2/`ディレクトリ以下の不要ファイルを消してほしい。
ついでに`f2/`ディレクトリ削除して、`images/`直下に移動してくれるとありがたい

2022-12-24 13:38 UTC, tt6-mzn commented on game/scripts/f2/r1/start.rpy
> +default f2r1_exsist_flag = False #
exist

2022-12-24 13:38 UTC, tt6-mzn commented on game/scripts/f2/r1/start.rpy
> +    if f1r1_jumplabel == "f2r2":
`f2r1_jumplabel`

2022-12-26 13:08 UTC, Esu0 approved these changes
動いた(多分)
ゲームとしては足りない部分があるからそこはまたあとで

2022-12-26 14:05 UTC, tt6-mzn approved these changes

2022-12-26 14:05 UTC, merged