クリック可能displayableにフォーカスしてると会話が読み進められないバグを修正
2022-4J-group-O/Main pull request #77
Opened 2023-01-10 13:30 UTC by Esu0

# 実装した内容

* イベント中はdisplayableにフォーカスしないようにした

## デバッグしてほしいところ

* イベント関連でバグがないか
* 会話が読み進められなくなることがないか

2023-01-10 20:00 UTC, tt6-mzn requested changes
menuにおけるopeningのイベント中にメニューにフォーカスが当たってしまう問題がある
まあ、menu事態暫定的なものなので特に問題はない気がするけど

2023-01-10 20:00 UTC, tt6-mzn commented on game/scripts/menu/events/l1_clicked.rpy
> +    show screen menu2_screen(False)
`opening.rpy`のイベントにもこれを追加するべきじゃない？

2023-01-12 12:31 UTC, Esu0 commented on game/scripts/menu/events/l1_clicked.rpy
> +    show screen menu2_screen(False)
修正した

2023-01-14 17:51 UTC, tt6-mzn approved these changes

2023-01-14 17:51 UTC, merged