object関連の不具合を解消
2022-4J-group-O/Main pull request #86
Opened 2023-01-12 15:10 UTC by Esu0

# 実装した内容

* Box.pngが表示されない問題を修正
* objectに関するファイル、ラベルなどの命名規則を一部変更(#85 を参照)
* objectが表示されていても、objectに対応するファイルがなければクリックイベントが発生しないように修正

## デバッグしてほしいところ

* 今まで定義したクリックイベントが動作するか
* objectが表示されていても、objectに対応するファイルがなければクリックイベントが発生しないか

2023-01-14 18:27 UTC, tt6-mzn commented on game/zz_late_eval/functions/function01.rpy
> +        print(path)
消し忘れ？

2023-01-14 18:57 UTC, tt6-mzn requested changes
Boxなどのバイナリオブジェクトのクリックイベントが呼び出されないもんだいがある。

2023-01-14 18:57 UTC, tt6-mzn commented on game/zz_late_eval/functions/function01.rpy
> +        return os.path.isfile(path) and (check_hash(path) or check_hash_binary(path))
`check_hash_binary`の仕様だと、引数にオブジェクトの名前のみを入れないといけない
`check_hash_binary(path)`->`check_hash_binary(os.path.basename(path))`として直すか、`check_hash_binary`の仕様を変えるか......
判断は任せる

2023-01-17 00:49 UTC, tt6-mzn requested changes

2023-01-17 00:49 UTC, tt6-mzn commented on game/zz_late_eval/functions/function01.rpy
> +        return os.path.isfile(path) and (check_hash(path) or check_hash_binary(path))
@Esu0 このreview見えてる？消えてたかも

2023-01-17 12:35 UTC, Esu0 commented
直した

2023-01-22 02:39 UTC, tt6-mzn approved these changes
LGTM

2023-01-22 02:39 UTC, merged