Add img f2r1
2022-4J-group-O/Main pull request #87
Opened 2023-01-13 14:26 UTC by nmrintel

# 実装した内容

* f2r1の画像合わせ
* 
## デバッグしてほしいところ
* 動くかな？
## 要検討
* f2r2へつながるドアを置く場所がない
* f1r3からCupを持ってくる過程

2023-01-14 19:31 UTC, tt6-mzn requested changes
古い書き方をモダンに変えたらOK
動作は問題なし。
ドアを置く場所がない問題は全く考慮していなかった。
全体右寄せして場所作るしかない気がする。
おってたいしょします。

2023-01-14 19:31 UTC, tt6-mzn commented on game_data/loadfile1/room1/Door
> +��G�=7E�dTz��8��h�ڧ�cTdo�bWO,6�
古いファイルが残っている

2023-01-14 19:31 UTC, tt6-mzn commented on game_data/loadfile1/room1/Drawer
> +�eH��W���zfO�Gi�g�:�S';,o
古いファイルが残っている

2023-01-14 19:31 UTC, tt6-mzn commented on game/scripts/f2/r1/start.rpy
>              f2r1_first = False
`f1r2_first`
この変数、使って無い？

2023-01-14 19:31 UTC, tt6-mzn commented on game/scripts/f2/r1/events/f2r1_success.rpy
>      $ event_end("f2r1.scloop")
`$ event_end("f2r2")`にすれば直接f2r1にジャンプできて、
`f2r1_jumplabel`を使わなくてよくなるはず

2023-01-14 19:31 UTC, tt6-mzn commented on game/scripts/f2/r1/start.rpy
>          if f2r1_exist_flag and f2r1_first:
これだと`Cup`のハッシュが検証されないから、32行目は、
`if "Cup" in read_room(loadfile2/room1/objectC/):`
とするべき
さらに、こうするとフラグ`f2r1_exist_flag`が必要なくなるはず

2023-01-14 19:31 UTC, tt6-mzn commented on game_data/loadfile1/room1/Chair
> +�fH�usFX�B��`�Е�r5�Td��v7(�
古いファイルが残っている

2023-01-19 14:38 UTC, Esu0 commented on game/scripts/f2/r1/start.rpy
>              f2r1_first = False
一回だけイベントが起こるようにする変数

2023-01-19 15:25 UTC, Esu0 commented
先に #94 をレビューしてください

2023-01-19 15:26 UTC, Esu0 commented
先に #86 をレビューしてください

2023-01-22 02:49 UTC, tt6-mzn approved these changes
LGTM

2023-01-22 02:49 UTC, merged